apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: galaxy
    app.kubernetes.io/name: galaxy
    app.kubernetes.io/version: "23.0"
  name: reftest-pv
  namespace: galaxy3
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 30Gi
  claimRef:
    namespace: galaxy3
    name: reftest-pvc
  csi:
    controllerPublishSecretRef:
      name: csi-s3-secret
      namespace: galaxy3
    driver: ru.yandex.s3.csi
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: galaxy3
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: galaxy3
    volumeAttributes:
      bucket: biorefdata
      capacity: "32212254720"
      mounter: s3fs
      options: -o endpoint=us-west-1 -o use_cache=/tmp -o public_bucket=1 -o enable_noobj_cache -o no_check_certificate -o kernel_cache -o ensure_diskfree=5000 -o max_background=1000 -o max_stat_cache_size=1000000 -o multipart_size=52 -o parallel_count=30 -o multireq_max=30 -o dbglevel=warn
    volumeHandle: biorefdata
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: galaxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: galaxy
    app.kubernetes.io/version: "23.0"
    helm.sh/chart: galaxy-5.7.1
  name: reftest-pvc
  namespace: galaxy3
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName:
  volumeMode: Filesystem
  volumeName: reftest-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: reftest
  namespace: galaxy3
spec:
  containers:
   - name: csi-s3-test-nginx
     image: nginx
     volumeMounts:
        - name: refdata-gxy
          mountPath: /cvmfs
  volumes:
    - name: refdata-gxy
      persistentVolumeClaim:
        claimName: reftest-pvc
